name: Clone Repository
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: manu/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: Build
        run: ./gradlew check