name: Clone Repository
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - name: Clone
        with:
          java-version: 15
      - name: Build
        run: ./gradlew check